#:schema node_modules/wrangler/config-schema.json
name = "sublink1"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "1444ee2d4d634e88ad8dfe6ede2a7d6c" }
]
